### ISSUE TITLE
How to work with Disambiguator

### ISSUE THREAD

**Issue by neerajb1** [botfront/rasa-addons#23]
Rasa Addons version (0.5.1): 
Rasa Core version (e.g. 0.11.11): 
Describe the problem: Hi i am new on Rasa. Could you please share how i can integrate and work with rasa-addon. I followed the readme given but i am getting below error.

ERROR:rasa_core.processor:Encountered an exception while running action 'action_disambiguate'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
ERROR:rasa_core.processor:'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\ReciprocieChatBot\myvenv\lib\site-packages\rasa_core\processor.py", line 338, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "D:\ReciprocieChatBot\myvenv\lib\site-packages\rasa_addons\disambiguation.py", line 144, in run
    disambiguation_message = self.get_disambiguation_message(dispatcher, self.rule, self.payloads, self.intents, tracker)
  File "D:\ReciprocieChatBot\myvenv\lib\site-packages\rasa_addons\disambiguation.py", line 122, in get_disambiguation_message
    "text"], "payload": i[1]} for i in zip(intents, payloads)])
  File "D:\ReciprocieChatBot\myvenv\lib\site-packages\rasa_addons\disambiguation.py", line 122, in <listcomp>
    "text"], "payload": i[1]} for i in zip(intents, payloads)])
TypeError: 'NoneType' object is not subscriptable
Hello intro

**Comment by znat** [comment]
Can you try again with 0.5.2?
